# Generated by Django 2.2 on 2019-05-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190502_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rates',
            field=models.IntegerField(default=0),
        ),
    ]
