# Generated by Django 2.2 on 2019-05-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190512_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rates',
        ),
    ]
