# Generated by Django 2.2 on 2019-05-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rates',
            field=models.IntegerField(default=0),
        ),
    ]
